const STORAGE_KEY = 'anesthesia-long-leave-v1';
const currentUser = { id: 'u1', name: '王小美', employedAt: '2025-03-01', probationPassed: true };
const sampleApplications = [
  { id: 'a1', user: '林安琪', userId: 'u2', plan: 'one', start: '2026-10-05', end: '2026-10-11', days: 7, status: 'pending', note: '' },
  { id: 'a2', user: '陳怡君', userId: 'u3', plan: 'one', start: '2026-10-06', end: '2026-10-12', days: 7, status: 'pending', note: '' },
  { id: 'a3', user: '張雅雯', userId: 'u4', plan: 'one', start: '2026-10-07', end: '2026-10-13', days: 7, status: 'pending', note: '' },
  { id: 'a4', user: '王小美', userId: 'u1', plan: 'one', start: '2026-08-10', end: '2026-08-16', days: 7, status: 'approved', note: '家庭旅遊' }
];
let apps = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || sampleApplications;
let leaveHistory = [];

const $ = (s) => document.querySelector(s);
function addCollapsibleData(container, title){if(!container||container.parentElement?.classList.contains('data-disclosure'))return;const details=document.createElement('details'),summary=document.createElement('summary');details.className='data-disclosure';summary.textContent=title;details.append(summary);container.parentNode.insertBefore(details,container);details.append(container);}
setTimeout(()=>{addCollapsibleData($('#account-list'),'展開人員帳號資料');const cvStatus=$('#course-file-status'),cvInput=$('#course-file'),cvLabel=cvInput?.previousElementSibling;if(cvStatus&&cvInput&&cvLabel&&!cvStatus.parentElement?.classList.contains('data-disclosure')){const details=document.createElement('details'),summary=document.createElement('summary');details.className='data-disclosure';summary.textContent='CV course 班表上傳';cvStatus.parentNode.insertBefore(details,cvLabel);details.append(summary,cvLabel,cvInput,cvStatus);}},0);
setTimeout(()=>{const form=$('#account-form'),button=form?.querySelector('button');if(form&&!$('#account-employed-at')){const label=document.createElement('label'),input=document.createElement('input');label.className='account-employed-label';label.textContent='到職日';input.id='account-employed-at';input.type='date';input.required=true;input.setAttribute('aria-label','到職日');label.append(input);form.insertBefore(label,button);}},0);
const dateInput = $('#start-date'); const endInput = $('#end-date'); const planInput = $('#plan');
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(apps)); if(window.firebaseBackend?.enabled) window.firebaseBackend.syncApplications(apps).then(()=>window.firebaseBackend.syncLeaveHistory(apps)).catch(error=>console.error('Firebase 同步失敗：',error)); }
function parseDate(s) { return new Date(`${s}T00:00:00`); }
function addDays(date, n) { const d = new Date(date); d.setDate(d.getDate() + n); return d; }
function iso(d) { return d.toISOString().slice(0,10); }
function daysBetween(start, end) { return Math.floor((parseDate(end) - parseDate(start)) / 86400000) + 1; }
function fiscalYear(date) { const d = parseDate(date); return d.getFullYear() + (d.getMonth() >= 6 ? 1 : 0); }
function fiscalLabel(year) { return `${year - 1911} 年度`; }
function formatDate(s) { const d = parseDate(s); return `${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')}`; }
function deadlineFor(start) {
  const d = parseDate(start), month = d.getMonth() - 3;
  const year = d.getFullYear() + Math.floor(month / 12), targetMonth = (month + 12) % 12;
  const lastDay = new Date(year, targetMonth + 1, 0).getDate();
  return new Date(year, targetMonth, Math.min(d.getDate(), lastDay), 23, 59, 59);
}
function overlaps(a,b) { return a.start <= b.end && a.end >= b.start; }
function planName(p) { return p === 'one' ? '方案一' : '方案二'; }
function statusName(s) { return ({pending:'待審核',approved:'已核准',rejected:'已駁回',cancelled:'已取消',lottery:'抽籤待定'})[s] || s; }
function statusTag(s) { return `<span class="tag ${s}">${statusName(s)}</span>`; }
function hasThreeMonths(user) { return (Date.now() - parseDate(user.employedAt)) / 86400000 >= 90 || user.probationPassed; }
function checkRequest(start, end, plan, applicantId = currentUser.id) {
  const checks = []; if (!start || !end) return { valid:false, checks:[['neutral','請選擇開始與結束日期']] };
  const days = daysBetween(start,end); const fy = fiscalYear(start); const deadline = deadlineFor(start); const now = new Date();
  const inSameFY = fiscalYear(end) === fy; const planOk = plan === 'one' ? days >= 5 && days <= 9 : days >= 10 && days < 18;
  const period = parseDate(start).getMonth() >= 6 ? 'jul-dec' : 'jan-jun';
  const mine = apps.filter(a => a.userId === applicantId && ['pending','approved','lottery'].includes(a.status) && fiscalYear(a.start) === fy);
  const existingPlan = mine[0]?.plan; const samePeriod = mine.some(a => a.plan === 'one' && (parseDate(a.start).getMonth() >= 6 ? 'jul-dec' : 'jan-jun') === period);
  checks.push([hasThreeMonths(activeAccount || currentUser) ? 'ok':'bad', '資格：任職滿 3 個月或試用期已滿']);
  checks.push([!activeAccount || activeAccount.employmentStatus === '在職' ? 'ok':'bad', !activeAccount || activeAccount.employmentStatus === '在職' ? '人員狀態：在職' : `人員狀態：${activeAccount.employmentStatus}，暫停提出申請`]);
  checks.push([planOk ? 'ok':'bad', `${planName(plan)}：${plan === 'one' ? '5–9' : '10–17'} 天（目前計算 ${days} 天）`]);
  checks.push([inSameFY ? 'ok':'bad', '申請日期須在同一院方年度內']);
  checks.push([!existingPlan || existingPlan === plan ? 'ok':'bad', '同一院方年度僅能選擇一種方案']);
  if (plan === 'one') checks.push([!samePeriod ? 'ok':'bad', !samePeriod ? `方案一的${period === 'jul-dec' ? '7–12 月' : '1–6 月'}時段尚未使用` : `方案一：此人已使用${period === 'jul-dec' ? '7–12 月' : '1–6 月'}名額，本次不可再次申請`]);
  if (plan === 'two') checks.push([mine.filter(a=>a.plan==='two').length === 0 ? 'ok':'bad', '方案二於院方年度內尚未申請']);
  checks.push([now <= deadline ? 'ok':'bad', `送件截止：${deadline.getFullYear()}/${deadline.getMonth()+1}/${deadline.getDate()} 23:59`]);
  checks.push([$('#cv1-check').checked ? 'ok':'bad', '已確認不與 CV1 course 衝突']);
  return { valid: checks.every(c=>c[0] === 'ok'), checks, days, deadline };
}
function refreshForm() { const applicantId=sessionUserId(),result = checkRequest(dateInput.value,endInput.value,planInput.value,applicantId); const list = $('#check-list'); list.innerHTML = result.checks.map(([state,text])=>`<li><span class="check-dot ${state}"></span><span>${text}</span></li>`).join(''); if(dateInput.value && endInput.value && result.days > 0) $('#calculation').innerHTML=`<strong>${result.days} 天</strong> 預約區間 ${formatDate(dateInput.value)}–${formatDate(endInput.value)}`; else $('#calculation').innerHTML='<span>請選擇日期以計算長假天數</span>'; if(result.deadline) $('#deadline-copy').textContent = `本次申請最晚於 ${result.deadline.getFullYear()}/${result.deadline.getMonth()+1}/${result.deadline.getDate()} 23:59 送出`;
}
function renderMine() { const mine = apps.filter(a=>a.userId===sessionUserId()); const fy = fiscalYear(new Date().toISOString().slice(0,10)); const active = mine.filter(a=>fiscalYear(a.start)===fy && ['pending','approved','lottery'].includes(a.status)); const p1=active.filter(a=>a.plan==='one').length,p2=active.filter(a=>a.plan==='two').length; $('#my-summary').innerHTML=`<article class="summary-card"><span>方案一已申請</span><b>${p1} / 2</b></article><article class="summary-card"><span>方案二已申請</span><b>${p2} / 1</b></article><article class="summary-card"><span>目前院方年度</span><b>${fiscalLabel(fy)}</b></article><article class="summary-card"><span>提示</span><b style="font-size:14px;font-family:inherit">核准以正式班表為準</b></article>`; $('#my-applications').innerHTML=mine.length?mine.map(a=>`<tr><td>${formatDate(a.start)}<br>至 ${formatDate(a.end)}</td><td>${planName(a.plan)}</td><td>${a.days} 天</td><td>${statusTag(a.status)}</td><td>${a.status==='pending'?`<button class="mini-btn danger" data-cancel="${a.id}">取消申請</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="5">尚無申請資料</td></tr>';
}
function groupSize(app) { return apps.filter(a=>['pending','approved','lottery'].includes(a.status)&&overlaps(a,app)).length; }
function renderDirector() { const active=apps.filter(a=>['pending','lottery'].includes(a.status)); const approved=apps.filter(a=>a.status==='approved'); const groups=apps.filter(a=>['pending','lottery'].includes(a.status)&&groupSize(a)>2); const uniqueLottery=new Set(groups.map(a=>a.start.slice(0,7))).size; $('#pending-count').textContent=active.length; $('#approved-count').textContent=approved.length; $('#lottery-count').textContent=uniqueLottery; $('#confirmed-count').textContent=approved.length; $('#director-applications').innerHTML=apps.map(a=>`<tr><td><strong>${a.user}</strong><br><small class="muted">${a.note||'—'}</small></td><td>${formatDate(a.start)}<br>– ${formatDate(a.end)}</td><td>${planName(a.plan)}<br>${a.days} 天</td><td>${groupSize(a)} 人 ${groupSize(a)>2?'<span class="tag lottery">需抽籤</span>':''}</td><td>${statusTag(a.status)}</td><td><div class="row-actions">${a.status==='pending'||a.status==='lottery'?`<button class="mini-btn" data-action="approve" data-id="${a.id}">核准</button><button class="mini-btn danger" data-action="reject" data-id="${a.id}">駁回</button>`:'—'}</div></td></tr>`).join(''); }
function renderHistory(){const table=$('#history-records');if(!table)return;const profileList=Array.isArray(accounts)?accounts:[],system=apps.filter(a=>a.status==='approved').map(a=>({id:a.id,userId:a.userId,name:a.user,employeeNo:profileList.find(p=>p.uid===a.userId)?.id||'',plan:a.plan,start:a.start,end:a.end,days:a.days,approvedAt:a.approvedAt||'',source:'system'})),records=[...leaveHistory.filter(record=>!system.some(item=>item.id===record.id)),...system],visible=isManager()?records:records.filter(record=>record.userId===sessionUserId());table.innerHTML=visible.length?visible.sort((a,b)=>String(b.start||'').localeCompare(String(a.start||''))).map(record=>`<tr><td>${record.name||'未設定'}</td><td>${record.employeeNo||'—'}</td><td>${record.start&&record.end?`${formatDate(record.start)}<br>至 ${formatDate(record.end)}`:'—'}</td><td>${record.plan?planName(record.plan):'—'}</td><td>${record.days||'—'}</td><td>${record.approvedAt?String(record.approvedAt).slice(0,10):'—'}</td></tr>`).join(''):'<tr><td colspan="6">尚無歷年長假紀錄</td></tr>';}
function renderAll(){renderMine();renderHistory();enrichMyTable();renderDirector();refreshForm();if($('#calendar-grid')&&calendarCursor)renderCalendar();if($('#account-list')&&Array.isArray(accounts))renderAccounts();if(typeof applyPermissions==='function')applyPermissions();}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function showView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(`#${view}-view`).classList.add('active');document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#page-title').textContent=({apply:'提出長假申請',mine:'我的長假申請',director:'審查狀態',rules:'規範與設定',calendar:'預約狀態',history:'歷年長假使用狀況',access:'帳號與資料串接'})[view];renderAll();}
document.querySelectorAll('.nav-link').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));document.querySelector('[data-view-target]').addEventListener('click',()=>showView('apply'));[dateInput,endInput,planInput,$('#cv1-check')].forEach(el=>el.addEventListener('change',refreshForm));dateInput.addEventListener('change',()=>{endInput.min=dateInput.value;if(endInput.value&&endInput.value<dateInput.value)endInput.value=dateInput.value;refreshForm();});
$('#cv-course-link').addEventListener('click',e=>{e.preventDefault();toast('CV course 班表連結已預留，待主管上傳班表後即可查看。');});
$('#leave-form').addEventListener('submit',e=>{e.preventDefault();const alert=$('#form-alert'),userId=sessionUserId(),userName=sessionUserName(),r=checkRequest(dateInput.value,endInput.value,planInput.value,userId);if(!r.valid||endInput.value<dateInput.value){alert.textContent='尚有規則未符合，請完成檢查後再送出。';alert.classList.remove('hidden');return;}alert.classList.add('hidden');apps.push({id:`a${Date.now()}`,user:userName,userId,applicantId:userId,plan:planInput.value,start:dateInput.value,end:endInput.value,days:r.days,status:'pending',submittedAt:new Date().toLocaleDateString('zh-TW'),note:$('#note').value.trim()});save();e.target.reset();refreshForm();toast(`已送出 ${userName} 的預約申請。`);showView(isManager()?'director':'mine');});
document.addEventListener('click',e=>{const cancel=e.target.dataset.cancel;if(cancel){apps=apps.map(a=>a.id===cancel?{...a,status:'cancelled'}:a);save();renderAll();toast('申請已取消，名額將不再列入抽籤。')}const action=e.target.dataset.action,id=e.target.dataset.id;if(action){apps=apps.map(a=>a.id===id?{...a,status:action==='approve'?'approved':'rejected'}:a);save();renderAll();toast(action==='approve'?'已核准並留下稽核紀錄。':'已駁回申請並通知申請人。');}});
$('#run-lottery').addEventListener('click',()=>{const candidates=apps.filter(a=>a.status==='pending');const crowded=candidates.filter(a=>groupSize(a)>2);if(!crowded.length){toast('目前沒有超過兩人的梯次，無須抽籤。');return;}const group=crowded.sort(()=>Math.random()-.5);const winners=new Set(group.slice(0,2).map(a=>a.id));apps=apps.map(a=>winners.has(a.id)?{...a,status:'approved',note:(a.note?'': '')+'（抽籤中籤）'}:group.some(g=>g.id===a.id)?{...a,status:'rejected',note:(a.note?'': '')+'（抽籤未中）'}:a);save();renderAll();toast('已完成示範抽籤；正式版將記錄抽籤批次與結果。');});
$('#reset-demo').addEventListener('click',()=>{apps=structuredClone(sampleApplications);save();renderAll();toast('已重設為示範資料。')});
const today = new Date(); const defaultStart = new Date(today.getFullYear(), today.getMonth()+3, 1); const defaultEnd=addDays(defaultStart,6); dateInput.value=iso(defaultStart);endInput.value=iso(defaultEnd); $('#fiscal-year-label').textContent=fiscalLabel(fiscalYear(dateInput.value));renderAll();

// Extension points for calendar, account, course, and personnel integrations.
var calendarCursor = new Date(today.getFullYear(), today.getMonth(), 1);
var calendarMode = 'month';
var activeAccount = null;
function sessionUserId(){return activeAccount?.uid||({staff:'u1',lin:'u2',chen:'u3',zhang:'u4',director:'m1'})[activeAccount?.id]||currentUser.id;}
function sessionUserName(){return activeAccount?.name||currentUser.name;}
const accountsKey = 'anesthesia-long-leave-accounts';
var accounts = JSON.parse(localStorage.getItem(accountsKey) || 'null') || [];
setTimeout(renderAll, 0);
const people = [
  { name:'王小美', id:'A001', employed:'2025/03/01', status:'試用期已滿', role:'麻醉專師' },
  { name:'林安琪', id:'A002', employed:'2024/08/15', status:'正式人員', role:'麻醉專師' },
  { name:'陳怡君', id:'A003', employed:'2023/05/01', status:'正式人員', role:'麻醉專師' },
  { name:'李主任', id:'M001', employed:'2018/07/01', status:'正式人員', role:'技術主任' }
];
function renderAccounts(){ const list=$('#account-list'); if(!list)return; list.innerHTML=accounts.map(a=>`<div class="account-row"><span><strong>${a.name}</strong> <small>${a.id}</small><br><small>${a.jobTitle||a.roleText||a.role}</small></span><select class="employment-status" data-employee-status="${a.uid}" ${isManager()?'':'disabled'}><option ${a.employmentStatus==='在職'?'selected':''}>在職</option><option ${a.employmentStatus==='育嬰留停'?'selected':''}>育嬰留停</option><option ${a.employmentStatus==='留職停薪'?'selected':''}>留職停薪</option><option ${a.employmentStatus==='離職'?'selected':''}>離職</option></select></div>`).join(''); }
document.addEventListener('change',async e=>{const uid=e.target.dataset.employeeStatus;if(!uid)return;if(!isManager()){toast('只有主管可變更人員狀態。');return;}try{await window.firebaseBackend.updateEmploymentStatus(uid,e.target.value);await loadFirebaseData();toast('人員狀態已同步更新。');}catch(error){toast(error.message||'人員狀態更新失敗。');}});
function enrichMyTable(){const rows=document.querySelectorAll('#my-applications tr'),mine=apps.filter(a=>a.userId===sessionUserId());rows.forEach((row,index)=>{const app=mine[index];if(app&&row.children.length===5){const cell=document.createElement('td');cell.textContent=app.submittedAt||'系統建檔';row.insertBefore(cell,row.children[0]);}});}
function isManager(){return !!activeAccount&&['技術主任','系統管理者','director','admin'].includes(activeAccount.role);}
function enrichReviewTable(manager){const table=$('#review-table');if(!table)return;table.classList.toggle('staff-review',!manager);document.querySelectorAll('#director-applications tr').forEach((row,index)=>{const app=apps[index];if(!app)return;const status=row.children[4];status.innerHTML=`${statusTag(app.status)}${app.checkPassed===false?'<br><span class="tag rejected">未檢核通過</span>':''}${app.approvedAt?`<br><small class="muted">核准日：${app.approvedAt}</small>`:''}`;if(manager&&row.children[5])row.children[5].innerHTML=`<div class="row-actions"><button class="mini-btn" data-action="approve" data-id="${app.id}">核准</button><button class="mini-btn danger" data-action="reject" data-id="${app.id}">駁回</button><button class="mini-btn" data-action="pending" data-id="${app.id}">改待審</button></div>`;});}
function applyPermissions(){const manager=isManager(),access=$('#access-nav'),login=$('#session-login'),logout=$('#session-logout'),reviewNav=$('#review-nav'),heading=$('#review-heading'),avatar=$('#session-avatar'),name=$('#session-name'),role=$('#session-role');if(access)access.style.display=manager?'':'none';document.querySelectorAll('.manager-only').forEach(el=>{if(!manager){el.style.display='none';return;}el.style.display=el.tagName==='TH'?'table-cell':el.tagName==='BUTTON'?'inline-block':'block';});if(reviewNav){reviewNav.style.display=manager?'':'none';reviewNav.innerHTML='<span>◫</span>主任管理';}if(heading)heading.textContent=manager?'主任管理':'審查狀態';if($('#director-view').classList.contains('active'))$('#page-title').textContent=manager?'主任管理':'審查狀態';if(login)login.classList.toggle('hidden',!!activeAccount);if(logout)logout.classList.toggle('hidden',!activeAccount);if(activeAccount){if(avatar)avatar.textContent=activeAccount.name.slice(0,1);if(name)name.textContent=activeAccount.name;if(role)role.textContent=activeAccount.jobTitle||activeAccount.roleText||activeAccount.role;}enrichReviewTable(manager);}
function eventFor(day){ return apps.filter(a=>['pending','approved','lottery'].includes(a.status)&&a.start<=day&&a.end>=day); }
function renderMonth(year,month,compact=false){ const first=new Date(year,month,1), days=new Date(year,month+1,0).getDate(), offset=first.getDay(),monthStart=`${year}-${String(month+1).padStart(2,'0')}-01`,monthEnd=`${year}-${String(month+1).padStart(2,'0')}-${String(days).padStart(2,'0')}`,people=[...new Set(apps.filter(a=>['pending','approved','lottery'].includes(a.status)&&a.start<=monthEnd&&a.end>=monthStart).map(a=>a.userId||a.user))].sort(),toneFor=e=>`person-tone-${people.indexOf(e.userId||e.user)%5}`; let html=compact?'':'<div class="calendar-weekday">日</div><div class="calendar-weekday">一</div><div class="calendar-weekday">二</div><div class="calendar-weekday">三</div><div class="calendar-weekday">四</div><div class="calendar-weekday">五</div><div class="calendar-weekday">六</div>'; for(let i=0;i<offset;i++)html+=compact?'<span></span>':'<div class="calendar-day muted-day"></div>'; for(let d=1;d<=days;d++){const day=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,events=eventFor(day); if(compact){html+=`<span class="${events.length?'has-event':''}">${d}</span>`;}else{html+=`<div class="calendar-day"><b>${d}</b>${events.slice(0,2).map(e=>`<span class="calendar-event ${e.status} ${toneFor(e)}">${e.user} · ${statusName(e.status)}</span>`).join('')}${events.length>2?'<span class="calendar-event lottery">更多申請</span>':''}</div>`;}} return html; }
function renderCalendar(){ const grid=$('#calendar-grid'),title=$('#calendar-title'); if(!grid||!title)return; const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth(); if(calendarMode==='month'){grid.classList.remove('year');title.textContent=`${y} 年 ${m+1} 月預約狀態`;grid.innerHTML=renderMonth(y,m);}else{grid.classList.add('year');title.textContent=`${y} 年全年預約狀態`;grid.innerHTML=Array.from({length:12},(_,i)=>`<article class="year-month"><h4>${i+1} 月</h4><div class="mini-calendar">${renderMonth(y,i,true)}</div></article>`).join('');}}
$('#calendar-prev').addEventListener('click',()=>{calendarCursor.setMonth(calendarCursor.getMonth()+(calendarMode==='month'?-1:-12));renderCalendar();});
$('#calendar-next').addEventListener('click',()=>{calendarCursor.setMonth(calendarCursor.getMonth()+(calendarMode==='month'?1:12));renderCalendar();});
$('#calendar-mode').addEventListener('change',e=>{calendarMode=e.target.value;renderCalendar();});
document.querySelectorAll('[data-title]').forEach(btn=>btn.addEventListener('click',()=>{$('#page-title').textContent=btn.dataset.title;}));
async function loadFirebaseData(){const data=await window.firebaseBackend.loadData();apps=data.applications;accounts=data.accounts;if(activeAccount){const refreshed=accounts.find(account=>account.uid===activeAccount.uid);if(refreshed)activeAccount=refreshed;}leaveHistory=data.leaveHistory||[];hospitalCalendar115=data.hospitalCalendar||hospitalCalendar115;people.splice(0,people.length,...data.accounts.map(a=>({name:a.name,id:a.id,employed:a.employedAt||'未設定',status:a.active?'啟用':'停用',role:a.jobTitle||a.roleText})));const managerPeople=$('#manager-person');if(managerPeople)managerPeople.innerHTML=data.accounts.filter(a=>a.role==='staff'&&a.active).map(a=>`<option value="${a.uid}">${a.name}（${a.id}）</option>`).join('')||'<option value="">請先建立人員帳號</option>';renderAll();}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const id=$('#login-id').value.trim(),pw=$('#login-password').value;if(!window.firebaseBackend?.enabled){toast('Firebase 尚在連線中，請稍後再試。');return;}try{activeAccount=await window.firebaseBackend.login(id,pw);await loadFirebaseData();$('#login-panel').classList.add('hidden');renderAll();toast(`已以${activeAccount.roleText||activeAccount.role}身分登入。`);}catch(error){activeAccount=null;toast(error.code==='auth/invalid-credential'?'員工編號／Email 或密碼不正確，請確認 Firebase Authentication 帳號設定。':(error.message||'登入失敗，請稍後再試。'));}});
$('#session-login').addEventListener('click',()=>{$('#login-panel').classList.remove('hidden');});
$('#session-logout').addEventListener('click',async()=>{try{await window.firebaseBackend?.logout();}catch(error){console.error(error)}activeAccount=null;$('#login-password').value='';$('#login-panel').classList.remove('hidden');showView('apply');renderAll();toast('您已登出系統。');});
$('#account-form').addEventListener('submit',async e=>{e.preventDefault();if(!isManager()){toast('只有技術主任或系統管理者可建立人員帳號，請先以主管帳號登入。');return;}const name=$('#account-name').value.trim(),id=$('#account-id').value.trim(),jobTitle=$('#account-role').value,password=$('#account-password').value,employedAt=$('#account-employed-at')?.value;if(!employedAt){toast('請輸入到職日期。');return;}if(accounts.some(a=>a.id===id)){toast('此員工編號已存在。');return;}try{await window.firebaseBackend.createEmployee({name,employeeNo:id,jobTitle,password,employedAt});await loadFirebaseData();e.target.reset();toast('帳號已建立，可用員工編號與個人密碼登入。');}catch(error){toast(error.message||'建立帳號失敗。');}});
$('#course-file').addEventListener('change',e=>{const file=e.target.files[0];$('#course-file-status').textContent=file?`已選擇：${file.name}（原型僅預覽，尚未上傳至資料庫）`:'尚未選擇檔案';});
$('#person-search').addEventListener('input',e=>{const term=e.target.value.trim().toLowerCase(),out=$('#person-results');if(!term){out.innerHTML='<p class="muted">可查詢任職日、試用狀態、長假紀錄與權限。</p>';return;}const found=people.filter(p=>`${p.name}${p.id}`.toLowerCase().includes(term));out.innerHTML=found.length?found.map(p=>`<div class="person-match"><strong>${p.name}</strong>（${p.id}）<br>${p.role} · 任職 ${p.employed} · ${p.status}</div>`).join(''):'<p class="muted">查無符合的人員。</p>';});
document.addEventListener('click',e=>{const action=e.target.dataset.action,id=e.target.dataset.id;if(!action||!id||!isManager())return;apps=apps.map(a=>a.id===id?{...a,status:action==='approve'?'approved':action==='reject'?'rejected':'pending',approvedAt:action==='approve'?new Date().toLocaleDateString('zh-TW'):null}:a);save();renderAll();toast(action==='approve'?'已核准並記錄核准日期。':action==='reject'?'已駁回申請。':'已改回待審狀態。');});
$('#run-lottery').addEventListener('click',()=>{if(!isManager())return;apps=apps.map(a=>a.status==='approved'&&!a.approvedAt?{...a,approvedAt:new Date().toLocaleDateString('zh-TW')}:a);save();renderAll();});
var pendingManagerRequest = null;
$('#manager-request-form').addEventListener('submit',e=>{e.preventDefault();if(!isManager())return;const personId=$('#manager-person').value,person={u2:'林安琪',u3:'陳怡君',u4:'張雅雯'}[personId],start=$('#manager-start').value,end=$('#manager-end').value,plan=$('#manager-plan').value,days=start&&end?daysBetween(start,end):0,fy=start?fiscalYear(start):null,period=start&&parseDate(start).getMonth()>=6?'7–12 月':'1–6 月',reasons=[];if(!start||!end||end<start)reasons.push('結束日期不得早於開始日期。');if(!(plan==='one'?days>=5&&days<=9:days>=10&&days<18))reasons.push(`${planName(plan)}天數需為 ${plan==='one'?'5–9':'10–17'} 天。`);const existing=fy?apps.filter(a=>a.userId===personId&&fiscalYear(a.start)===fy&&['pending','lottery','approved'].includes(a.status)):[];const otherPlan=existing.find(a=>a.plan!==plan),samePlan=existing.filter(a=>a.plan===plan);if(otherPlan)reasons.push(`此人本院方年度已申請${planName(otherPlan.plan)}，不可混用方案。`);if(plan==='one'&&samePlan.some(a=>(parseDate(a.start).getMonth()>=6?'7–12 月':'1–6 月')===period))reasons.push(`此人已申請方案一的${period}場次，不可重複申請。`);if(plan==='two'&&samePlan.length)reasons.push('此人本院方年度已申請方案二，不可重複申請。');if(start&&new Date()>deadlineFor(start))reasons.push(`已超過送件截止日 ${formatDate(iso(deadlineFor(start)))}。`);const valid=reasons.length===0;pendingManagerRequest={personId,person,start,end,plan,days,checkPassed:valid,checkReasons:reasons};const history=existing.length?existing.map(a=>`${formatDate(a.start)}–${formatDate(a.end)}／${planName(a.plan)}／${statusName(a.status)}`).join('<br>'):'無同院方年度既有申請';$('#manager-confirm-summary').innerHTML=`<strong class="${valid?'result-pass':'result-fail'}">檢核${valid?'通過':'未通過'}</strong><br>申請人：${person}<br>方案：${planName(plan)}（${days} 天）<br>日期：${start&&end?`${formatDate(start)} 至 ${formatDate(end)}`:'尚未完整填寫'}<br>送件者：${activeAccount.name}<hr><strong>既有申請比對</strong><br>${history}<hr><strong>${valid?'檢核結果：符合規範':'未通過原因'}</strong><br>${valid?'可送出申請。':reasons.map(r=>`• ${r}`).join('<br>')}`;$('#manager-confirm').disabled=false;$('#manager-confirm').textContent='確認';$('#manager-confirm-modal').classList.remove('hidden');});
$('#manager-cancel').addEventListener('click',()=>{$('#manager-confirm-modal').classList.add('hidden');pendingManagerRequest=null;});
$('#manager-confirm').addEventListener('click',()=>{if(!pendingManagerRequest||!isManager())return;const r=pendingManagerRequest;apps.push({id:`a${Date.now()}`,user:r.person,userId:r.personId,applicantId:r.personId,plan:r.plan,start:r.start,end:r.end,days:r.days,status:'pending',checkPassed:r.checkPassed,checkReasons:r.checkReasons,submittedAt:new Date().toLocaleDateString('zh-TW'),note:`由 ${activeAccount.name} 代為提出`});save();$('#manager-confirm-modal').classList.add('hidden');$('#manager-request-form').reset();pendingManagerRequest=null;renderAll();toast(`已代 ${r.person} 送出長假申請。`);});

// Registered in capture phase to use the Firebase person UID instead of legacy demo IDs.
$('#manager-request-form').addEventListener('submit',e=>{if(!window.firebaseBackend?.enabled||!isManager())return;e.preventDefault();e.stopImmediatePropagation();const personId=$('#manager-person').value,account=accounts.find(a=>a.uid===personId),start=$('#manager-start').value,end=$('#manager-end').value,plan=$('#manager-plan').value,days=start&&end?daysBetween(start,end):0,reasons=[];if(!account){toast('請先在帳號管理建立人員帳號。');return;}if(!start||!end||end<start)reasons.push('結束日期不得早於開始日期。');if(!(plan==='one'?days>=5&&days<=9:days>=10&&days<18))reasons.push(`${planName(plan)}天數需為 ${plan==='one'?'5–9':'10–17'} 天。`);const existing=apps.filter(a=>a.userId===personId&&fiscalYear(a.start)===fiscalYear(start)&&['pending','lottery','approved'].includes(a.status)),period=start&&parseDate(start).getMonth()>=6?'7–12 月':'1–6 月';if(existing.some(a=>a.plan!==plan))reasons.push('此人本院方年度已使用另一方案，不可混用。');if(plan==='one'&&existing.some(a=>a.plan==='one'&&(parseDate(a.start).getMonth()>=6?'7–12 月':'1–6 月')===period))reasons.push(`此人已使用方案一的${period}名額。`);if(plan==='two'&&existing.some(a=>a.plan==='two'))reasons.push('此人本院方年度已申請方案二。');if(start&&new Date()>deadlineFor(start))reasons.push(`已超過送件截止日 ${formatDate(iso(deadlineFor(start)))}。`);pendingManagerRequest={personId,person:account.name,start,end,plan,days,checkPassed:reasons.length===0,checkReasons:reasons};$('#manager-confirm-summary').innerHTML=`<strong class="${reasons.length?'result-fail':'result-pass'}">檢核${reasons.length?'未通過':'通過'}</strong><br>申請人：${account.name}<br>方案：${planName(plan)}（${days} 天）<br>日期：${start&&end?`${formatDate(start)} 至 ${formatDate(end)}`:'尚未完整填寫'}<br>送件者：${activeAccount.name}<hr><strong>${reasons.length?'未通過原因':'檢核結果'}</strong><br>${reasons.length?reasons.map(r=>`• ${r}`).join('<br>'):'可送出申請。'}`;$('#manager-confirm-modal').classList.remove('hidden');},true);

// 115 年馬偕白班人員上班日曆：僅農曆年與院方連續四日以上假期不列入長假天數。
var hospitalCalendar115 = { year:115, source:'馬偕醫院上班日曆_115.01-12.pdf', excludedDates:['2026-02-15','2026-02-16','2026-02-17','2026-02-18','2026-02-19','2026-09-25','2026-09-26','2026-09-27','2026-09-28'], events:[{start:'2026-02-15',end:'2026-02-19',label:'農曆年'},{start:'2026-09-25',end:'2026-09-28',label:'院方連續假期'}] };
var rawDaysBetween = daysBetween;
daysBetween = function(start,end){ if(!start||!end||end<start)return 0;const excluded=new Set(hospitalCalendar115?.excludedDates||[]);let count=0;for(let day=parseDate(start);day<=parseDate(end);day=addDays(day,1))if(!excluded.has(iso(day)))count++;return count; };
function datesInRange(start,end){const days=[];for(let day=parseDate(start);day<=parseDate(end);day=addDays(day,1))days.push(iso(day));return days;}
function bookingGroupFor(userId){return accounts.find(a=>a.uid===userId)?.bookingGroup||null;}
function groupCapacityDates(start,end,userId){const group=bookingGroupFor(userId);if(!group||!start||!end)return [];return datesInRange(start,end).filter(day=>apps.filter(a=>['pending','approved','lottery'].includes(a.status)&&bookingGroupFor(a.userId)===group&&a.start<=day&&a.end>=day).length>=2);}
var baseCheckRequest = checkRequest;
checkRequest = function(start,end,plan,applicantId=currentUser.id){const result=baseCheckRequest(start,end,plan,applicantId),conflicts=groupCapacityDates(start,end,applicantId);if(bookingGroupFor(applicantId)){result.checks.splice(-1,0,[conflicts.length?'bad':'ok',conflicts.length?'同職群每日可預約人數已達 2 人上限':'同職群每日預約人數未超過 2 人']);result.valid=result.checks.every(check=>check[0]==='ok');}return result;};
var baseRefreshForm = refreshForm; refreshForm = function(){baseRefreshForm();document.querySelectorAll('#check-list li').forEach(item=>{const text=item.textContent||'';if(text.includes('申請日期須在同一院方年度內')||text.includes('同職群每日'))item.remove();if(text.includes('資格：任職滿 3 個月或試用期已滿')){const date=activeAccount?.employedAt;if(date){const passed=hasThreeMonths(activeAccount);item.lastElementChild.textContent=`資格：到職日 ${formatDate(date)}（${passed?'已滿 3 個月':'未滿 3 個月'}）`;}else item.lastElementChild.textContent='資格：尚未設定到職日或試用期狀態';}});};
function normalizeImportRow(row){const aliases={employeeNo:['員工編號','員工代號','員工號','工號','employeeNo','employeeid'],name:['姓名','name'],password:['密碼','password'],jobTitle:['職稱','職務','jobTitle','title'],employedAt:['到職日','到職日期','employedAt']},value=key=>{const found=Object.keys(row).find(column=>aliases[key].includes(String(column).replace(/\s/g,'')));return found===undefined?'':String(row[found]??'').trim();};return {employeeNo:value('employeeNo'),name:value('name'),password:value('password'),jobTitle:value('jobTitle'),employedAt:value('employedAt'),probationPassed:true};}
async function readStaffImport(file){if(file.name.toLowerCase().endsWith('.json')){const payload=JSON.parse(await file.text());return payload.employees||[];}if(file.name.toLowerCase().endsWith('.xlsx')){if(!window.XLSX)throw new Error('Excel 匯入元件尚未載入，請確認網路後重新整理。');const book=window.XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true}),sheetName=book.SheetNames.find(name=>window.XLSX.utils.sheet_to_json(book.Sheets[name],{header:1,defval:''}).some(row=>row.includes('到職日')||row.includes('到職日期')))||book.SheetNames[0],rows=window.XLSX.utils.sheet_to_json(book.Sheets[sheetName],{defval:'',raw:false,dateNF:'yyyy-mm-dd'}),entries=rows.map(normalizeImportRow).filter(row=>row.employeeNo||row.name||row.password||row.jobTitle||row.employedAt);if(entries.every(row=>row.employedAt&&!row.password)){entries.forEach(row=>{const d=new Date(row.employedAt);if(!Number.isNaN(d))row.employedAt=d.toISOString().slice(0,10);});return entries;}const incomplete=entries.find(row=>!row.employeeNo||!row.name||!row.password||!row.jobTitle);if(incomplete)throw new Error('Excel 每筆資料都必須包含：員工編號、姓名、密碼、職稱。');return entries;}throw new Error('僅接受 .xlsx 或 .json 人員匯入檔。');}
$('#staff-import-file').addEventListener('change',async e=>{const file=e.target.files[0],status=$('#staff-import-status');if(!file)return;if(!isManager()){status.textContent='匯入未執行：只有技術主任或系統管理者可批次建立人員帳號，請先以主管帳號登入。';e.target.value='';return;}try{const entries=await readStaffImport(file);if(!entries.length)throw new Error('找不到人員資料。');if(entries.every(row=>row.employedAt&&!row.password)){status.textContent=`正在依員工編號更新 ${entries.length} 筆到職日…`;const result=await window.firebaseBackend.updateEmploymentDates(entries);await loadFirebaseData();status.textContent=`完成：已更新 ${result.updated} / ${result.total} 筆到職日。`;toast(status.textContent);return;}if(!confirm(`將建立 ${entries.length} 個 Firebase 帳號並寫入人員資料，是否繼續？`))return;status.textContent=`正在建立 ${entries.length} 個帳號，請勿關閉頁面…`;const results=await window.firebaseBackend.bulkCreateEmployees(entries,hospitalCalendar115),failed=results.filter(r=>!r.ok);await loadFirebaseData();status.textContent=failed.length?`完成；${results.length-failed.length} 筆成功、${failed.length} 筆需處理。`:`完成：已建立 ${results.length} 筆人員帳號並同步 115 年行事曆。`;toast(status.textContent);}catch(error){status.textContent=`匯入失敗：${error.message||error}`;}});
document.addEventListener('submit',e=>{if(e.target.id!=='manager-request-form')return;const personId=$('#manager-person').value,conflicts=groupCapacityDates($('#manager-start').value,$('#manager-end').value,personId);if(conflicts.length){e.preventDefault();e.stopImmediatePropagation();toast('同職群每日可預約人數已達 2 人上限，請調整日期。');}},true);
